<?php

namespace EasyWorkflowBundle\Repository;

/**
 * FlowLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlowLogRepository extends \Doctrine\ORM\EntityRepository
{
}
