<?php

namespace EasyWorkflowBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EasyWorkflowBundle\Entity\FlowNodes;

/**
 * FlowNodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlowNodesRepository extends EntityRepository
{
    public function findWithHandlers($id)
    {
        /** @var FlowNodes $flowNode */
        $flowNode = $this->find($id);
        $em       = $this->getEntityManager();
        $flowNode->nextHandlers = $em->getRepository('EasyWorkflowBundle:Group')->getHandlersBy($flowNode->getGroups());
        return $flowNode;
    }
}
