<?php

namespace EasyWorkflowBundle\Repository;

/**
 * FlowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlowRepository extends \Doctrine\ORM\EntityRepository
{
}
