<?php

namespace EasyWorkflowBundle\Repository;

/**
 * FlowNodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlowNodesRepository extends \Doctrine\ORM\EntityRepository
{
}
