<?php

namespace EasyWorkflowBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
    public function findByIds($groupIds)
    {
        return $this->createQueryBuilder('group_repository')
            ->where('group_repository.id in(:groupIds)')
            ->setParameter('groupIds', $groupIds)
            ->getQuery()
            ->getResult();
    }

    public function getHandlersBy($groups)
    {
        return $this->createQueryBuilder('group_repository')
            ->innerJoin('group_repository.users', 'users')
            ->select('users.id,users.username')
            ->getQuery()
            ->getResult();
    }
}
