<?php

namespace EasyWorkflowBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
    public function findByIds($groupIds)
    {
        return $this->createQueryBuilder('groupRepository')
            ->where('groupRepository.id in(:groupIds)')
            ->setParameter('groupIds', $groupIds)
            ->getQuery()
            ->getResult();
    }
}
