<?php

namespace EasyWorkflowBundle\Repository;

/**
 * LeaveFlowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaveFlowRepository extends \Doctrine\ORM\EntityRepository
{
}
