easy_workflow:
    resource: "@EasyWorkflowBundle/Controller/"
    type:     annotation
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
