services:
    easy_workflow.flow_listenr:
        class: EasyWorkflowBundle\EventListener\ControllerBeforeListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    mongo_client:
        class: MongoClient
        # if not using a username and password
        arguments: ['mongodb://127.0.0.1:27017']
    session.handler.mongo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        arguments: ['@mongo_client', '%mongo.session.options%']
    easy_workflow.twig_extension:
        class: EasyWorkflowBundle\Twig\EasyWorkflowExtension
        public: false
        tags:
            - { name: twig.extension }