services:
    easy_workflow.example:
        class: EasyWorkflowBundle\EventListener\FlowListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
